import Head from "next/head";
import Image from "next/image";
import Body from "../components/Body";
import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
    const darkMode = false;
    return (
        <div
            className={`${darkMode} ? bg-[rgb(32,33,36)] h-screen overflow-x-hidden flex flex-col justify-center items-center`}
        >
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Body />
            <Footer />
        </div>
    );
}
